default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: db/fitofit_development.sqlite3

test:
  <<: *default
  database: db/fitofit_test.sqlite3

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch('FITO_DB_NAME') %>
  username: <%= ENV.fetch('FITO_DB_USER') %>
  password: <%= ENV.fetch('FITO_DB_PASS') %>
  host: <%= ENV.fetch('FITO_DB_HOST') %>
  socket: /tmp/mysql.sock
  collation: utf8mb3_general_ci
